install.packages('tidyverse')
install.packages('devtools')
install.packages('styler')
install.packages('lubridate')
install.packages('glue')
install.packages('stringr')
install.packages('fs')
install.packages('uuid')