-- CREATE USER nlamarre WITH PASSWORD '9a7U3I9RGe9sL1JsulsX';
-- GRANT CONNECT ON DATABASE postgres TO nlamarre;
-- GRANT USAGE ON SCHEMA public TO nlamarre;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO nlamarre;


CREATE USER abc WITH PASSWORD '123;
GRANT CONNECT ON DATABASE postgres TO abc;
GRANT USAGE ON SCHEMA public TO abc;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO abc;





