-- CREATE USER nlamarre WITH PASSWORD '9a7U3I9RGe9sL1JsulsX';
-- GRANT CONNECT ON DATABASE postgres TO nlamarre;
-- GRANT USAGE ON SCHEMA public TO nlamarre;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO nlamarre;


CREATE USER ppereira WITH PASSWORD '!wEwC4S;zZT<uWWK';
GRANT CONNECT ON DATABASE postgres TO ppereira;
GRANT USAGE ON SCHEMA public TO ppereira;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ppereira;





