library(redditor)
con <- postgres_connector(POSTGRES_PORT = 5432, POSTGRES_HOST = Sys.getenv('POWEREDGE'))
send_message("Transferring submissions from s3 to postgres")
s3_submissions_to_postgres(con = con)
send_message("submissions from s3 to postgres complete")
