library(redditor)
con <- postgres_connector(POSTGRES_PORT = 5433)
send_message("Transferrind submissions from s3 to postgres")
s3_submissions_to_postgres(con = con)
send_message("submissions from s3 to postgres complete")
