export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_INSTANCES = "GET_INSTANCES";
export const SET_CURRENT_INSTANCE = "SET_CURRENT_INSTANCE";
export const CLEAR_CURRENT_INSTANCE = "CLEAR_CURRENT_INSTANCE";
export const UPDATE_INSTANCE = "UPDATE_INSTANCE";
export const FILTER_INSTANCES = "FILTER_INSTANCES";
export const CLEAR_INSTANCE_FILTER = "CLEAR_INSTANCE_FILTER";
export const INSTANCE_ERROR = "INSTANCE_ERROR";
export const CLEAR_INSTANCES = "CLEAR_INSTANCES";
export const SET_LOADING = "SET_LOADING";

export const GET_SECURITY_GROUP = "GET_SECURITY_GROUP";
export const CREATE_KEY_FILE = "CREATE_KEY_FILE";
